GO_EASY_ON_ME=1
THEOS=../theos

include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME=USBDeviceFramework
USBDeviceFramework_FILES=USBDevice.m
USBDeviceFramework_FRAMEWORKS=Foundation CoreFoundation IOKit

include $(THEOS)/makefiles/framework.mk

